"""ExecutorNet -- lightweight CNN target network for EMNIST classification."""

import torch
import torch.nn as nn


class ExecutorNet(nn.Module):
    """Small CNN that serves as both a standalone classifier and the
    target architecture whose weights are generated by ModulatorNet."""

    def __init__(self, num_classes: int = 47):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, 3, 1),
            nn.ReLU(),
            nn.Conv2d(32, 64, 3, 1),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Dropout(0.25),
        )
        self.classifier = nn.Sequential(
            nn.Linear(9216, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.features(x)
        x = torch.flatten(x, 1)
        x = self.classifier(x)
        return x
